@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

GradPad *-right-> "1" UniqueModuleList
GradPad *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueModuleList
UniqueTagList -[hidden]down- UniqueModuleList

UniqueTagList *-right-> "*" Tag
UniqueModuleList o-right-> Module

Module -up-> "*" Tag

Module *--> ModuleCode
Module *--> ModularCredits
Module *--> ModuleName
@enduml
