@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":GradPadParser" as GradPadParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete CS2103T")
activate LogicManager

LogicManager -> GradPadParser : parseCommand("delete CS2103T")
activate GradPadParser

create DeleteCommandParser
GradPadParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> GradPadParser
deactivate DeleteCommandParser

GradPadParser -> DeleteCommandParser : parse("CS2103T")
activate DeleteCommandParser

DeleteCommandParser -> ParserUtil : parseModuleCode("CS2103T")
activate ParserUtil

ParserUtil --> DeleteCommandParser : code
deactivate ParserUtil

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> GradPadParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> GradPadParser
destroy DeleteCommandParser

GradPadParser --> LogicManager : d
deactivate GradPadParser

LogicManager -> LogicManager : handleStall()
activate LogicManager

LogicManager --> LogicManager : confirmationPrompt
deactivate LogicManager

[<-- LogicManager : confirmationPrompt
deactivate LogicManager

[-> LogicManager : execute("yes")
activate LogicManager

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deleteModule("CS2103T")
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
