@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":GradPadParser" as GradPadParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant "f:FindCommand" as FindCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find CS2103T")
activate LogicManager

LogicManager -> GradPadParser : parseCommand("find CS2103T")
activate GradPadParser

create FindCommandParser
GradPadParser -> FindCommandParser
activate FindCommandParser

FindCommandParser --> GradPadParser
deactivate FindCommandParser

GradPadParser -> FindCommandParser : parse(" CS2103T")
activate FindCommandParser

create FindCommand
FindCommandParser -> FindCommand
activate FindCommand

FindCommand --> FindCommandParser : f
deactivate FindCommand

FindCommandParser --> GradPadParser : f
deactivate FindCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindCommandParser -[hidden]-> GradPadParser
destroy FindCommandParser

GradPadParser --> LogicManager : f
deactivate GradPadParser

LogicManager -> FindCommand : execute()
activate FindCommand

FindCommand -> Model : updateFilteredModuleList()
activate Model

Model --> FindCommand
deactivate Model

create CommandResult
FindCommand -> CommandResult
activate CommandResult

CommandResult --> FindCommand
deactivate CommandResult

FindCommand --> LogicManager : result
deactivate FindCommand

[<--LogicManager
deactivate LogicManager
@enduml
