@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyGradPad <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class GradPad
Class ReadOnlyGradPad
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Module {
Class Module
Class ModuleName
Class ModuleCode
Class ModularCredits
Class UniqueModuleList
}

Package Tag {
Class Tag
Class UniqueTagMap
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

GradPad .up.|> ReadOnlyGradPad

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" GradPad
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

GradPad *--> "1" UniqueModuleList
GradPad *--> "1" UniqueTagMap
UniqueTagMap o--> "*" Tag
UniqueModuleList o--> "*" Module
Module *--> ModuleCode
Module *--> ModularCredits
Module *--> ModuleName
Module --> "*" Tag

ModuleCode -[hidden]right-> ModularCredits
ModularCredits -[hidden]right-> ModuleName

ModelManager -->"1" Module : filtered list
@enduml
