@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":GradPadParser" as GradPadParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedGradPad" as VersionedGradPad MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> GradPadParser : parseCommand(undo)
activate GradPadParser

create UndoCommand
GradPadParser -> UndoCommand
activate UndoCommand

UndoCommand --> GradPadParser
deactivate UndoCommand

GradPadParser --> LogicManager : u
deactivate GradPadParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoGradPad()
activate Model

Model -> VersionedGradPad : undo()
activate VersionedGradPad

VersionedGradPad -> VersionedGradPad :resetData(ReadOnlyGradPad)
VersionedGradPad --> Model :
deactivate VersionedGradPad

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
